# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "652c69b590f3c0e854729f8bf32ddac2"
name = "store-locator"
handle = "store-locator-175"
application_url = "https://store-locator-one.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_app_proxy,write_products,write_themes"

[auth]
redirect_urls = [
  "https://store-locator-one.vercel.app/auth/callback",
  "https://store-locator-one.vercel.app/auth/shopify/callback",
  "https://store-locator-one.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://store-locator-one.vercel.app/app-proxy/store-locator"
subpath = "store-locator"
prefix = "apps"

[pos]
embedded = false
