# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc0568978e5a7a64c4020dc35c935330"
name = "store-locator"
handle = "store-locator-176"
application_url = "https://store-locator-one.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_products,read_themes,write_themes"

[auth]
redirect_urls = ["https://store-locator-one.vercel.app/auth/callback", "https://store-locator-one.vercel.app/auth/shopify/callback", "https://store-locator-one.vercel.app/api/auth/callback"]

[app_proxy]
url = "https://store-locator-one.vercel.app/app-proxy/store-locator"
subpath = "store-locator"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
