# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc0568978e5a7a64c4020dc35c935330"
name = "store-locator"
handle = "store-locator-176"
application_url = "https://black-dpi-lease-pad.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_app_proxy,write_products,write_themes"

[auth]
redirect_urls = [
  "https://black-dpi-lease-pad.trycloudflare.com/auth/callback",
  "https://black-dpi-lease-pad.trycloudflare.com/auth/shopify/callback",
  "https://black-dpi-lease-pad.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
